name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "tests/**"
      - "package-lock.json"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "packages/**"
      - "tests/**"
      - "package-lock.json"
      - ".github/workflows/tests.yml"

defaults:
  run:
    shell: "bash"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn ci
      - run: yarn run test:main

  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn ci
      - run: yarn run test:preload

  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn ci
      - run: yarn run test:renderer

  e2e:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn ci
