name: Typechecking
on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.vue"
      - "**/tsconfig.json"
      - "package-lock.json"
      - ".github/workflows/typechecking.yml"
  pull_request:
    paths:
      - "**.ts"
      - "**.vue"
      - "**/tsconfig.json"
      - "package-lock.json"
      - ".github/workflows/typechecking.yml"

defaults:
  run:
    shell: "bash"

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # Need for yarn >=7.7
          cache: "yarn"

      # TODO: Install not all dependencies, but only those required for this workflow
      - name: Install dependencies
        run: yarn ci

      - run: yarn run typecheck
